name: Ejemplo de GitHub Actions con secreto condicional

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Paso 2
        if: ${{ env.OPCION == '1' }}
        run: echo "Este es el  cuando vale 3"
        
      - name: Paso 2
        run: echo "Este es el  cuando vale 3"
